name: "AI Changelog (GitHub Models)"
description: "Generate a human-friendly changelog from git history using GitHub Models. No external API keys needed."
author: "Arjun Krishna / decoded-cipher"

branding:
  icon: "book-open"
  color: "blue"

inputs:
  range:
    description: >
      Git revision range (e.g. v1.0.0..HEAD). 
      If empty, uses last tag..HEAD, or HEAD if no tags.
    required: false
    default: ""
  output_path:
    description: "File path to write changelog markdown to."
    required: false
    default: "CHANGELOG.md"
  model:
    description: "GitHub Models ID (e.g. openai/gpt-4o-mini)."
    required: false
    default: "openai/gpt-4o-mini"
  create_pr:
    description: "If true, use a dedicated branch, commit changelog, push, and create/update a PR to the base branch (no direct push to base)."
    required: false
    default: "false"
  changelog_branch:
    description: "Branch to use for changelog commits when create_pr is true."
    required: false
    default: "auto/changelog"
  base_branch:
    description: "Base branch to merge into the changelog branch and to open the PR into (e.g. master)."
    required: false
    default: "master"

outputs:
  changelog:
    description: "Generated changelog markdown."

runs:
  using: "composite"
  steps:
    - name: Ensure jq is installed
      shell: bash
      run: |
        set -e
        if ! command -v jq >/dev/null 2>&1; then
          echo "jq not found, installing..."
          sudo apt-get update -y
          sudo apt-get install -y jq
        fi

    - name: Generate changelog with GitHub Models
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        INPUT_RANGE: ${{ inputs.range }}
        OUTPUT_PATH: ${{ inputs.output_path }}
        MODEL_ID: ${{ inputs.model }}
        CREATE_PR: ${{ inputs.create_pr }}
        CHANGELOG_BRANCH: ${{ inputs.changelog_branch }}
        BASE_BRANCH: ${{ inputs.base_branch }}
        PROMPT_PATH: ${{ github.action_path }}/prompt.txt
      run: |
        set -euo pipefail

        if [ -z "${GITHUB_TOKEN:-}" ]; then
          echo "GITHUB_TOKEN is not available. Make sure permissions.models=read is set."
          exit 1
        fi

        # Optional: use changelog branch and sync with base (for create_pr mode)
        if [ "${CREATE_PR}" = "true" ]; then
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin "$BASE_BRANCH"
          if git show-ref --quiet refs/remotes/origin/"$CHANGELOG_BRANCH"; then
            git fetch origin "$CHANGELOG_BRANCH"
            git checkout -B "$CHANGELOG_BRANCH" origin/"$CHANGELOG_BRANCH"
            git merge origin/"$BASE_BRANCH" --no-edit
          else
            git checkout -b "$CHANGELOG_BRANCH"
          fi
        fi

        # Decide git range
        RANGE="$INPUT_RANGE"
        if [ -z "$RANGE" ]; then
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -z "$LAST_TAG" ]; then
            RANGE="HEAD"
          else
            RANGE="${LAST_TAG}..HEAD"
          fi
        fi

        echo "Using git range: $RANGE"

        # Collect commit history (hash | date | subject)
        COMMITS_FILE=".ai-changelog-commits.txt"
        git log "$RANGE" --pretty=format:"%h | %ad | %s" --date=iso > "$COMMITS_FILE" || true

        if [ ! -s "$COMMITS_FILE" ]; then
          echo "No commits found for range: $RANGE"
          echo "No changes." > "$OUTPUT_PATH"
          {
            echo "changelog<<EOF"
            echo "No changes."
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
          exit 0
        fi

        # Build prompt file
        PROMPT_FILE=".ai-changelog-prompt.txt"
        if [ -f "$PROMPT_PATH" ]; then
          cat "$PROMPT_PATH" > "$PROMPT_FILE"
        else
          echo "Error: Prompt file not found at $PROMPT_PATH"
          exit 1
        fi
        echo "" >> "$PROMPT_FILE"
        cat "$COMMITS_FILE" >> "$PROMPT_FILE"

        # Build JSON payload using jq
        PAYLOAD_FILE=".changelog-payload.json"
        jq -Rs --arg model "$MODEL_ID" '
          {
            model: $model,
            messages: [
              {
                role: "user",
                content: .
              }
            ]
          }
        ' "$PROMPT_FILE" > "$PAYLOAD_FILE"

        # Call GitHub Models API
        RESPONSE_FILE=".ai-changelog-response.json"
        curl -sS "https://models.github.ai/inference/chat/completions" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -d @"$PAYLOAD_FILE" > "$RESPONSE_FILE"

        # Extract the content
        CHANGELOG_CONTENT=$(jq -r '.choices[0].message.content // empty' "$RESPONSE_FILE")

        if [ -z "$CHANGELOG_CONTENT" ]; then
          echo "Model returned empty content or unexpected response:"
          cat "$RESPONSE_FILE"
          exit 1
        fi

        # Write to output file
        echo "$CHANGELOG_CONTENT" > "$OUTPUT_PATH"
        echo "Changelog written to $OUTPUT_PATH"

        # Expose as action output
        {
          echo "changelog<<EOF"
          echo "$CHANGELOG_CONTENT"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"

        # Optional: commit, push and create PR
        if [ "${CREATE_PR}" = "true" ]; then
          git add "$OUTPUT_PATH"
          if git diff --staged --quiet; then
            echo "No changelog changes to commit."
          else
            git commit -m "chore: update $OUTPUT_PATH [skip ci]"
            git push origin "$CHANGELOG_BRANCH"
          fi
          gh pr create \
            --base "$BASE_BRANCH" \
            --head "$CHANGELOG_BRANCH" \
            --title "chore: update $OUTPUT_PATH" \
            --body "Auto-generated changelog from recent commits. Review and merge when ready." \
            || true
        fi
